-- 'rejudging' is a first-class submission status in the Go layer
-- (internal/model/submission.go: StatusRejudging SubmissionStatus = "rejudging"),
-- but it was never added to the `verdict` enum. That left the constant
-- unwritable against submissions.status (type verdict) and made migration
-- 000038_multi_bot fail on any database applying it for the first time:
--
--   ERROR: invalid input value for enum verdict: "rejudging"
--
-- IMPORTANT: PostgreSQL refuses to *reference* a freshly added enum value in the
-- same transaction that added it ("unsafe use of new value of enum type"),
-- and golang-migrate wraps each migration in one transaction. So this migration
-- ONLY adds the value; the partial index that references it lives in 000055,
-- which runs in its own transaction and can therefore see 'rejudging'.
--
-- This split is why 000038's index is recreated in 000055 rather than here.
ALTER TYPE verdict ADD VALUE IF NOT EXISTS 'rejudging';
